# Generated by Django 3.2.5 on 2021-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_categoria',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
