# Generated by Django 3.2.5 on 2021-08-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20210821_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='id_respuesta',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
    ]
