# Generated by Django 3.2.5 on 2021-08-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20210829_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='id_respuesta',
        ),
    ]
