# Generated by Django 3.2.5 on 2021-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_remove_respuesta_id_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='total_preguntas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
