# Generated by Django 3.2.5 on 2021-08-31 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_partida_total_preguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 12, 56, 34, 296384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='partida',
            name='total_preguntas',
            field=models.IntegerField(null=True),
        ),
    ]
